config/routes.rb
Bugtaks::Application.routes.draw do

    
  resources :bug_categories

  resources :projects do
    resources :bug_lists do
		  resources :bug_posts do
		    resources :bug_comments 
		  end
	  end

    resources :tasks do
      resources :task_ledgers do
        member do
          put 'stop'
          get 'start'
        end
      end
    end
    
    member do
      post 'join'
      post 'unjoin'
      get 'present_bug_lists'
      get 'present_task_ledgers'
    end
  end
  

  

  resources :rights

  resources :roles

  resources :users

  resources :tasks
  resources :user_notifications
  match '/:action', :controller => 'application'

   root :to => 'application#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  @@STATUSES = ["Active", "Inactive", "Completed"]
  
  has_and_belongs_to_many :tasks
  has_many :task_ledgers, :dependent=>:destroy
  has_many :bug_lists, :dependent=>:destroy
  has_and_belongs_to_many :users

  validates_presence_of :name, :status
  validates_uniqueness_of :name
  validate :start_date_cannot_be_greater_than_end_date
  validates :status, :inclusion=>{:in=>@@STATUSES, :message=>"%{value} is not a valid status."}
  
 
  def self.statuses
    return @@STATUSES
  end
  
  def can_be_joined_by_user_id?(user_id)
    return !(self.users.include? User.find(user_id))
  end
  
  def total_manhours
  	return "%.2f" % self.task_ledgers.sum(:duration)
  end
  
  def longest_task_name
    tl = longest_task
  	tl.keys[tl.values.index tl.values.max]
  end
  
  def longest_task_value
	  tl = longest_task
		"%.2f" %  tl.values.max
  end
  
  def latest_task_ledger
  	self.task_ledgers.order("start_datetime desc").limit(1)  
  end
  
  private 
    def start_date_cannot_be_greater_than_end_date
      if !end_date.nil? and start_date > end_date
        errors.add(:start_date, "can't be later than end date")
      end
    end
    
    def longest_task
  		self.task_ledgers.joins(:task).group("task_ledgers.task_id, tasks.name").sum(:duration)
  	end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :require_user_privilege, :except => [:index,:join, :unjoin, :new, :create]
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    redirect_to projects_path unless @project.user_ids.include? session[:user_id]
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])

		@project.destroy
		respond_to do |format|
		  format.html { redirect_to projects_url }
		  format.json { head :ok }
		end
  end
  
  
  def join
    user = User.find(session[:user_id])
    @project = Project.find(params[:id])
    user.join(@project)
  end
  
  
  def unjoin
    user = User.find(session[:user_id])
    @project = Project.find(params[:id])
    user.unjoin(@project)  
  end
  
  def present_bug_lists
    @project = Project.find(params[:id])
  end
  
  def present_task_ledgers
    @project = Project.find(params[:id])
  end
  
  private 
    def require_user_privilege
      project = Project.find(params[:id])
      redirect_to projects_url unless project.user_ids.include?session[:user_id]
    end
  
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def sorted_task_ledgers(label,project, sort_key)
		link_to label, present_task_ledgers_project_path(project) + "?sort=#{sort_key}", :remote=>true
	end
end

app/views/projects/_bug_lists.html.erb
<p>
  <b> Bug Lists: </b>
  <% unless @project.bug_lists.empty? %>
	  <table>
  	  <% @project.bug_lists.find_each do |bug_list| %>
  	    <tr>
  	      <td> <%= bug_list.title%> </td> 
  	      <td> <%= "(#{bug_list.no_of_closed_bugs} out of #{bug_list.no_of_bugs})" %> </td>
  	      <td><%= link_to 'New Bug Post', new_project_bug_list_bug_post_path(bug_list.project_id, bug_list.id) %></td>
    	    <%= render :partial=>'bug_posts', :locals=>{:bug_list=>bug_list} %>
  	    </tr>
  	  <% end %>
  	</table>
  <% end %>
  <%= link_to 'New Bug List', new_project_bug_list_path(@project.id) %>
</p>

app/views/projects/_bug_posts.html.erb
<p>
  <table class="bug_posts">
    <% bug_list.bug_posts.find_each do |bp| %>
		  <tr>  
		    <td> 
		    	<%= link_to bp.title, project_bug_list_bug_post_path(bug_list.project_id, bug_list.id, bp.id)%> 
		    </td>
		    <td>
		      <%= bp.status %>
		    </td>
		    
		  </tr>
		<% end %>
  </table>
  

</p>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.select :status, Project.statuses %>
  </div>
  
   <div class="field">
    <%= f.label :tasks_ids, 'Tasks' %><br />
    <ul>
     <% Task.where(:task_id=>nil).order(:name).each do |t|%>
       <li>
         <%= check_box_tag "project[task_ids][]", t.id, @project.tasks.include?(t) %>
	   <%= t.name %>
       </li>
     <% end %>
    </ul>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_join_unjoin.html.erb
   <% if project.can_be_joined_by_user_id? session[:user_id] %>
		 <%= form_tag join_project_path(project.id), :method=>:post, :remote=>true do %>
			 <%= submit_tag "Join Project" %>
		 <% end %>	 
   <% else %>
		 <%= form_tag unjoin_project_path(project.id), :method=>:post, :remote=>true do %>
			 <%= submit_tag "Unjoin Project" %>
		 <% end %>	 
   <% end %>

app/views/projects/_task_ledgers.html.erb
<div id="task_ledgers">
	<% unless @project.nil? %>
		<p>
			<b> Task Ledger: </b>
			<table border=1>
				<tr>
		 	<th> <%= sorted_task_ledgers 'Task', @project, 'name' %> </th>
		 	<th> <%= sorted_task_ledgers 'Start', @project, 'start_datetime' %> </th>
		 	<th> End </th>
		 	<th> <%= sorted_task_ledgers 'User', @project, 'screen_name' %> </th>
		 	<th> <%= sorted_task_ledgers 'Duration(hrs)', @project, 'duration' %> </th>
		 	<th> Notes </th>
			<th> Options </th>
				</tr>
			<% task_ledgers = TaskLedger.find_with_sort_key(@project.id, params[:sort])%>
			<% for t in task_ledgers %>
				<tr>
		 	<td <%= "class=overriden" if t.is_manual %>> <%= t.task.name %> </td>
		 	<td> <%= t.start_datetime.ctime %> </td>
		 	<td> <%= t.end_datetime.ctime if !t.end_datetime.nil? %> </td>
		 	<td> <%= t.user.screen_name %> </td>
		 	<td> <%= "%.2f" % t.duration if !t.duration.nil? %> </td>
		 	<td> <%= simple_format(t.description.squeeze(" "),{}, :sanitize=>true) unless t.description.nil? %> </td>
			<td class='delete_item'> 
				<% if t.user_id == session[:user_id] && t.status != "Active" %>
			<%= link_to 'Edit', edit_project_task_task_ledger_path(@project.id, t.task.id, t.id), :confirm=>"Override?" %> 
			<%= link_to 'Destroy', project_task_task_ledger_path(@project.id, t.task.id, t.id), :method=>:delete, :remote=>true, :confirm=>"Are you sure?" %> 
			
				<% end %>
			</td>
				</tr>
			<% end %>
			</table>
		</p>
	<% end %>
</div>

app/views/projects/_tasks.html.erb
<div id="tasks">
	<p>
		<% if !@project.nil? && session[:task_ledger_id].nil? %>	
			<b> Tasks: </b>
			<% @project.tasks.each do |t| %>
				<% Task.subtasks(t) do |s| %>
					  <% case s %>
				      <% when Task %>
				        <li>
				          <%= s.name %>
				          <span class="start_task">
				          <%= link_to 'Start', start_project_task_task_ledger_path(@project.id, s.id), :remote=>true %>
				          <%= link_to 'Override', new_project_task_task_ledger_path(@project.id,s.id) %>
				          </span>
				        </li>          
				      <% when 1 %>
				      <ul>
				<% when -1%> 
				      </ul>
				  	<% end %>
				
				<% end %>
			<% end %>
		<% else %>
			<b> There is still a current active task. Multitasking is inefficient.</b>
		<% end %>
	</p>
</div>

app/views/projects/_users.html.erb
<ul>
	<% users.each do |u| %>
    <li> <%= link_to u.screen_name, u %> </li>
	<% end %>
</ul>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= link_to project.name, project %></td>
    <td><%= project.start_date %></td>
    <td><%= project.end_date %></td>
    <td><%= project.status %></td>
    <td>
    <div id="join_unjoin_<%= project.id %>">
			<%= render :partial=>'join_unjoin', :locals=>{:project=>project} %>
    </div>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/join.js.erb
$('#join_unjoin_<%= @project.id %>').html("<%= escape_javascript render(:partial=>'join_unjoin', :locals=>{:project=>@project}) %>");

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/present_bug_lists.js.erb
$('#content').html("<%= escape_javascript render 'bug_lists' %>");
bindFunctions();

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>
<input type="hidden" name="real_project_id" id="real_project_id" value="<%= @project.id%>" />

<table border=1>
  <tr>
    <td><b>Project:</b></td>
    <td> <%= @project.name %> </td>
    <td rowspan=2><b>Description:</b></td>
    <td rowspan=2><%= simple_format(@project.description, {},:sanitize=>true) %> </td>
    <td><b>Total ManHours: </b> </td>
    <td> <%= @project.total_manhours %></td>
  </tr>
  <tr>
    <td> <b>Start Date:</b> </td>
    <td> <%= @project.start_date %> </td>
    <td><b>Longest Task: </b> </td>
    <td> <%= @project.longest_task_name %></td>
  </tr>
  
  <tr>
    <td><b>End Date:</b></td>
    <td> <%= @project.end_date %> </td>
		<td><b>Status:</b></td>
    <td> <%= @project.status %> </td>
    <td><b>Longest Task(hrs): </b> </td>
    <td> <%= @project.longest_task_value %></td>
  </tr>
</table>
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Destroy', @project, confirm: 'Are you sure?', method: :delete %> |
<%= link_to 'Back', projects_path %> |
<%= link_to 'Show Bugs', present_bug_lists_project_path(@project), :remote=>true %> |
<%= link_to 'Show Task Ledger', present_task_ledgers_project_path(@project), :remote=>true %>
<p>
  <b> Developers: </b>
  <%= render :partial=>'users', :locals=>{:users=>@project.users}%>
</p>

<div id="content">
		<%= render :partial=>'tasks' %>
		<%= render :partial=>'task_ledgers' %>
</div>

app/views/projects/unjoin.js.erb
$('#join_unjoin_<%= @project.id %>').html("<%= escape_javascript render(:partial=>'join_unjoin', :locals=>{:project=>@project}) %>");