config/routes.rb
Bugtaks::Application.routes.draw do

    
  resources :bug_categories

  resources :projects do
    resources :bug_lists do
		  resources :bug_posts do
		    resources :bug_comments 
		  end
	  end

    resources :tasks do
      resources :task_ledgers do
        member do
          put 'stop'
          get 'start'
        end
      end
    end
    
    member do
      post 'join'
      post 'unjoin'
      get 'present_bug_lists'
      get 'present_task_ledgers'
    end
  end
  

  

  resources :rights

  resources :roles

  resources :users

  resources :tasks
  resources :user_notifications
  match '/:action', :controller => 'application'

   root :to => 'application#index'

end

app/models/bug_list.rb
class BugList < ActiveRecord::Base
  @@STATUSES = ["Active", "Completed"]

  belongs_to :project
  belongs_to :user
  has_many :bug_posts, :dependent=>:destroy
  
  validates_presence_of :title, :status, :project_id
  validates_uniqueness_of :title
  validates :status, :inclusion =>{:in => @@STATUSES, :message=>"%{value} is not a valid status"}

 
  def self.statuses
    return @@STATUSES
  end
  
  def no_of_unclosed_bugs
    return self.bug_posts.where("status <> 'Closed'").count
  end
  
  def no_of_closed_bugs
    return self.bug_posts.where(:status=>"Closed").count
  end
  
  def no_of_bugs
    return self.bug_posts.count
  end
  

end

app/controllers/bug_lists_controller.rb
class BugListsController < ApplicationController
  # GET /bug_lists
  # GET /bug_lists.json
  def index
    @bug_lists = BugList.where(:project_id=>params[:project_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bug_lists }
    end
  end

  # GET /bug_lists/1
  # GET /bug_lists/1.json
  def show
    @bug_list = BugList.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bug_list }
    end
  end

  # GET /bug_lists/new
  # GET /bug_lists/new.json
  def new
    @bug_list = BugList.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bug_list }
    end
  end

  # GET /bug_lists/1/edit
  def edit
    @bug_list = BugList.find(params[:id])
  end

  # POST /bug_lists
  # POST /bug_lists.json
  def create
    @bug_list = BugList.new(params[:bug_list])
		@bug_list.user_id = session[:user_id]
    respond_to do |format|
      if @bug_list.save
        format.html { redirect_to @bug_list.project, notice: 'Bug list was successfully created.' }
        format.json { render json: @bug_list, status: :created, location: @bug_list }
      else
        format.html { render action: "new" }
        format.json { render json: @bug_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bug_lists/1
  # PUT /bug_lists/1.json
  def update
    @bug_list = BugList.find(params[:id])
		@bug_list.user_id = session[:user_id]
    respond_to do |format|
      if @bug_list.update_attributes(params[:bug_list])
        format.html { redirect_to @bug_list.project, notice: 'Bug list was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @bug_list.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /bug_lists/1
  # DELETE /bug_lists/1.json
  def destroy
    @bug_list = BugList.find(params[:id])
    @bug_list.destroy

    respond_to do |format|
      format.html { redirect_to project_bug_lists_url }
      format.json { head :ok }
    end
  end
end

app/helpers/bug_lists_helper.rb
module BugListsHelper
end

app/views/bug_lists/_bug_posts.html.erb
<p>
  <b>Bug Posts:</b> <br />

  <table>
    <% bug_list.bug_posts.find_each do |bp| %>
		  <tr>  
		    <td> 
		    	<%= link_to bp.title, project_bug_list_bug_post_path(bug_list.project_id, bug_list.id, bp.id)%> 
		    </td>
		    <td>
		      <%= link_to 'Destroy', [bug_list.project, bug_list, bp], :method=> :delete, :confirm=>'Are you sure?' %>
		    </td>
		    
		  </tr>
		<% end %>
  </table>
  
  <%= link_to 'New Bug Post', new_project_bug_list_bug_post_path(bug_list.project_id, bug_list.id) %>
</p>

app/views/bug_lists/_form.html.erb
<%= form_for(@bug_list, :url=>"/projects/#{params[:project_id]}/bug_lists/#{params[:id]}") do |f| %>
  <% if @bug_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bug_list.errors.count, "error") %> prohibited this bug_list from being saved:</h2>

      <ul>
      <% @bug_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
 <%= f.hidden_field :project_id, :value=>params[:project_id] %>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.select :status, BugList.statuses %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bug_lists/edit.html.erb
<h1>Editing bug_list</h1>

<%= render 'form' %>

<%= link_to 'Show', [@bug_list.project, @bug_list] %> |
<%= link_to 'Back', project_bug_lists_path %>

app/views/bug_lists/index.html.erb
<h1>Listing bug_lists</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Status</th>
    <th>User</th>
    <th>Bug posts</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bug_lists.each do |bug_list| %>
  <tr>
    <td><%= bug_list.title %></td>
    <td><%= bug_list.description %></td>
    <td><%= bug_list.status %></td>
    <td><%= bug_list.user.screen_name %></td>
    <td><%= bug_list.bug_posts_count %></td>
    <td><%= link_to 'Show', project_bug_list_path(bug_list.project_id,bug_list) %></td>
    <td><%= link_to 'Edit', edit_project_bug_list_path(bug_list.project_id,bug_list) %></td>
    <td><%= link_to 'Destroy', project_bug_list_path(bug_list.project_id, bug_list), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bug List', new_project_bug_list_path %>

app/views/bug_lists/new.html.erb
<h1>New bug_list</h1>

<%= render 'form' %>

<%= link_to 'Back', project_bug_lists_path %>

app/views/bug_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @bug_list.title %>
</p>

<p>
  <b>Project:</b>
  <%= @bug_list.project.name %>
</p>

<p>
  <b>Description:</b>
  <%= @bug_list.description %>
</p>

<p>
  <b>Status:</b>
  <%= @bug_list.status %>
</p>

<p>
  <b>User:</b>
  <%= @bug_list.user.screen_name %>
</p>

<p>
  <b>Bug posts count:</b>
  <%= @bug_list.bug_posts_count %>
</p>

<%= render :partial=>'bug_posts',:locals=>{:bug_list=>@bug_list} %>
 
<%= link_to 'Edit', edit_project_bug_list_path(@bug_list.project_id,@bug_list) %> |
<%= link_to 'Back', project_bug_lists_path %>