config/routes.rb
Bugtaks::Application.routes.draw do

    
  resources :bug_categories

  resources :projects do
    resources :bug_lists do
		  resources :bug_posts do
		    resources :bug_comments 
		  end
	  end

    resources :tasks do
      resources :task_ledgers do
        member do
          put 'stop'
          get 'start'
        end
      end
    end
    
    member do
      post 'join'
      post 'unjoin'
      get 'present_bug_lists'
      get 'present_task_ledgers'
    end
  end
  

  

  resources :rights

  resources :roles

  resources :users

  resources :tasks
  resources :user_notifications
  match '/:action', :controller => 'application'

   root :to => 'application#index'

end

app/models/bug_category.rb
class BugCategory < ActiveRecord::Base
  has_many :bug_posts
  
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/controllers/bug_categories_controller.rb
class BugCategoriesController < ApplicationController
  # GET /bug_categories
  # GET /bug_categories.json
  def index
    @bug_categories = BugCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bug_categories }
    end
  end

  # GET /bug_categories/1
  # GET /bug_categories/1.json
  def show
    @bug_category = BugCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bug_category }
    end
  end

  # GET /bug_categories/new
  # GET /bug_categories/new.json
  def new
    @bug_category = BugCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bug_category }
    end
  end

  # GET /bug_categories/1/edit
  def edit
    @bug_category = BugCategory.find(params[:id])
  end

  # POST /bug_categories
  # POST /bug_categories.json
  def create
    @bug_category = BugCategory.new(params[:bug_category])

    respond_to do |format|
      if @bug_category.save
        format.html { redirect_to @bug_category, notice: 'Bug category was successfully created.' }
        format.json { render json: @bug_category, status: :created, location: @bug_category }
      else
        format.html { render action: "new" }
        format.json { render json: @bug_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bug_categories/1
  # PUT /bug_categories/1.json
  def update
    @bug_category = BugCategory.find(params[:id])

    respond_to do |format|
      if @bug_category.update_attributes(params[:bug_category])
        format.html { redirect_to @bug_category, notice: 'Bug category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @bug_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bug_categories/1
  # DELETE /bug_categories/1.json
  def destroy
    @bug_category = BugCategory.find(params[:id])
    @bug_category.destroy

    respond_to do |format|
      format.html { redirect_to bug_categories_url }
      format.json { head :ok }
    end
  end
end

app/helpers/bug_categories_helper.rb
module BugCategoriesHelper
end

app/views/bug_categories/_form.html.erb
<%= form_for(@bug_category) do |f| %>
  <% if @bug_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bug_category.errors.count, "error") %> prohibited this bug_category from being saved:</h2>

      <ul>
      <% @bug_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bug_categories/edit.html.erb
<h1>Editing bug_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @bug_category %> |
<%= link_to 'Back', bug_categories_path %>

app/views/bug_categories/index.html.erb
<h1>Listing bug_categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bug_categories.each do |bug_category| %>
  <tr>
    <td><%= bug_category.name %></td>
    <td><%= bug_category.description %></td>
    <td><%= link_to 'Show', bug_category %></td>
    <td><%= link_to 'Edit', edit_bug_category_path(bug_category) %></td>
    <td><%= link_to 'Destroy', bug_category, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bug category', new_bug_category_path %>

app/views/bug_categories/new.html.erb
<h1>New bug_category</h1>

<%= render 'form' %>

<%= link_to 'Back', bug_categories_path %>

app/views/bug_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @bug_category.name %>
</p>

<p>
  <b>Description:</b>
  <%= @bug_category.description %>
</p>


<%= link_to 'Edit', edit_bug_category_path(@bug_category) %> |
<%= link_to 'Back', bug_categories_path %>