config/routes.rb
Bugtaks::Application.routes.draw do

    
  resources :bug_categories

  resources :projects do
    resources :bug_lists do
		  resources :bug_posts do
		    resources :bug_comments 
		  end
	  end

    resources :tasks do
      resources :task_ledgers do
        member do
          put 'stop'
          get 'start'
        end
      end
    end
    
    member do
      post 'join'
      post 'unjoin'
      get 'present_bug_lists'
      get 'present_task_ledgers'
    end
  end
  

  

  resources :rights

  resources :roles

  resources :users

  resources :tasks
  resources :user_notifications
  match '/:action', :controller => 'application'

   root :to => 'application#index'

end

app/models/bug_comment.rb
class BugComment < ActiveRecord::Base
  belongs_to :bug_post
  belongs_to :user
  
  validates_presence_of :body, :bug_post_id, :user_id
  
	after_create :send_notification
	
	private
		def send_notification
		  bug_path = "/projects/#{self.bug_post.bug_list.project_id}/bug_lists/#{self.bug_post.bug_list_id}/bug_posts/#{self.bug_post_id}"
		  notification = UserNotification.new
		  notification.title = "#{self.user.screen_name} commented on #{self.bug_post.title}"
		  notification.body = "%.30s..." % self.body
		  notification.notification_url = bug_path
		  notification.sent_to = self.bug_post.posted_for
		  notification.sent_by = self.user
		  notification.save
		end
end

app/controllers/bug_comments_controller.rb
class BugCommentsController < ApplicationController
  # GET /bug_comments
  # GET /bug_comments.json
  def index
    @bug_comments = BugComment.where(:bug_post_id=>params[:bug_post_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bug_comments }
    end
  end

  # GET /bug_comments/1
  # GET /bug_comments/1.json
  def show
    @bug_comment = BugComment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bug_comment }
    end
  end

  # GET /bug_comments/new
  # GET /bug_comments/new.json
  def new
    @bug_comment = BugComment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bug_comment }
    end
  end

  # GET /bug_comments/1/edit
  def edit
    @bug_comment = BugComment.find(params[:id])
  end

  # POST /bug_comments
  # POST /bug_comments.json
  def create
    @bug_comment = BugComment.new(params[:bug_comment])

    respond_to do |format|
      if @bug_comment.save
        format.html { redirect_to project_bug_list_bug_post_path(params[:project_id], params[:bug_list_id], params[:bug_post_id]), notice: 'Bug comment was successfully created.' }
        format.json { render json: @bug_comment, status: :created, location: @bug_comment }
      else
        format.html { render action: "new" }
        format.json { render json: @bug_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bug_comments/1
  # PUT /bug_comments/1.json
  def update
    @bug_comment = BugComment.find(params[:id])

    respond_to do |format|
      if @bug_comment.update_attributes(params[:bug_comment])
        format.html { redirect_to project_bug_list_bug_post_path(params[:project_id], params[:bug_list_id], params[:bug_post_id]), notice: 'Bug comment was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @bug_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bug_comments/1
  # DELETE /bug_comments/1.json
  def destroy
    @bug_comment = BugComment.find(params[:id])
    @bug_comment.destroy

    respond_to do |format|
      format.html { redirect_to project_bug_list_bug_post_path(params[:project_id], params[:bug_list_id], params[:bug_post_id]), notice: 'Bug comment was deleted.' }
      format.json { head :ok }
    end
  end
end

app/helpers/bug_comments_helper.rb
module BugCommentsHelper
end

app/views/bug_comments/_form.html.erb
<%= form_for(@bug_comment, :url=>project_bug_list_bug_post_bug_comment_path(params[:project_id], params[:bug_list_id], params[:bug_post_id])) do |f| %>
  <% if @bug_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bug_comment.errors.count, "error") %> prohibited this bug_comment from being saved:</h2>

      <ul>
      <% @bug_comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <%= f.hidden_field :bug_post_id, :value=>params[:bug_post_id] %>
  <%= f.hidden_field :user_id, :value=>session[:user_id] %>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :img_url %><br />
    <%= f.text_field :img_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bug_comments/edit.html.erb
<h1>Editing bug_comment</h1>

<%= render 'form' %>


<%= link_to 'Back', project_bug_list_bug_post_path(params[:project_id], params[:bug_list_id], params[:bug_post_id]) %>

app/views/bug_comments/index.html.erb
<h1>Listing bug_comments</h1>

<table>
  <tr>
    <th>Bug post</th>
    <th>Body</th>
    <th>User</th>
    <th>Img url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bug_comments.each do |bug_comment| %>
  <tr>
    <td><%= bug_comment.bug_post.title %></td>
    <td><%= bug_comment.body %></td>
    <td><%= bug_comment.user.screen_name %></td>
    <td><%= bug_comment.img_url %></td>
    <td><%= link_to 'Show', bug_comment %></td>
    <td><%= link_to 'Edit', edit_project_bug_list_bug_post_bug_comment_path(bug_comment.bug_post.bug_list.project_id, bug_comment.bug_post.bug_list_id, bug_comment.bug_post_id, bug_comment.id) %></td>
    <td><%= link_to 'Destroy', project_bug_list_bug_post_bug_comment_path(bug_comment.bug_post.bug_list.project_id, bug_comment.bug_post.bug_list_id, bug_comment.bug_post_id, bug_comment.id), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bug comment', new_bug_comment_path %>

app/views/bug_comments/new.html.erb
<h1>New bug_comment</h1>

<%= render 'form' %>

<%= link_to 'Back', project_bug_list_bug_post_path %>

app/views/bug_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Bug post:</b>
  <%= @bug_comment.bug_post %>
</p>

<p>
  <b>Body:</b>
  <%= @bug_comment.body %>
</p>

<p>
  <b>User:</b>
  <%= @bug_comment.user %>
</p>

<p>
  <b>Img url:</b>
  <%= @bug_comment.img_url %>
</p>


<%= link_to 'Edit', edit_bug_comment_path(@bug_comment) %> |
<%= link_to 'Back', bug_comments_path %>